# For more details on the format and content:
# https://github.com/robocorp/rcc/blob/master/docs/recipes.md#what-is-in-condayaml
# Tip: Adding a link to the release notes of the packages helps maintenance and security.

channels:
  - conda-forge
dependencies:
  - python=3.9.13
  - tesseract=4.1.1
  - pip=22.1.2
  - nodejs=16.14.2
  - pip:
    - robotframework-browser==13.3.0
    - rpaframework==22.2.1
    - rpaframework-aws==5.0.0
    - rpaframework-google==6.1.1
    - rpaframework-recognition==5.0.0
rccPostInstall:
  - rfbrowser init
